language: ruby
bundler_args: --without development
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
#  - rbx-18mode
#  - rbx-19mode
gemfile:
  - gemfiles/minitest-1.7
  - gemfiles/minitest-2
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/minitest-2
