language: ruby
bundler_args: --without development -j4
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby-19mode
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
gemfile:
  - gemfiles/Gemfile.minitest-4
  - gemfiles/Gemfile.minitest-5
