language: ruby
bundler_args: --without development
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ree
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ruby-head
  - jruby-head
gemfile:
  # - gemfiles/minitest-1
  # - gemfiles/minitest-2
  # - gemfiles/minitest-3
  # - gemfiles/minitest-4
  - gemfiles/minitest-5
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/minitest-2
